roles:
  - "user"
  - "admin"
  - "superadmin"

routes:
  - prefix: "/api/users"
    target: "http://users_service:8081"
    skip_auth: false

  - prefix: "/api/users/delete"
    target: "http://users_service:8081"
    skip_auth: false
    required_roles:
      - "superadmin"
      - "admin"

  - prefix: "/api/reports"
    target: "http://reports_service:8082"
    skip_auth: false
    required_roles:
        - "superadmin"
        - "admin"
        - "user"

  - prefix: "/api/admin"
    target: "http://admin_service:8083"
    skip_auth: false
    required_roles:
      - "superadmin"

  # редирект-маршрут: вместо проксирования отвечаем 302 на target + путь запроса
  # с strip_first_prefix: true первый сегмент пути вырезается: /inference/api/v1 -> login_service/login/api/v1
  - prefix: "/inference"
    target: "http://login_service:8084/login"
    skip_auth: true
    redirect: true
    strip_first_prefix: true

blacklist:
  - "10.0.0.0/8"

users:
  - id: 1
    login: "admin"
    password: "adminpass"
    email: "admin@example.com"
    full_name: "Admin"
    role: "superadmin"
